#!/bin/bash

#curl --request   PUT \
# --header    "Content-Type: application/json" \
# --write-out "%{http_code}\n" \
# --data '{"value": "127"}' \
# http://localhost:13801/kvs/keys/x

curl --request  GET \
 --header    "Content-Type: application/json" \
 --write-out "%{http_code}\n" \
 http://localhost:13801/kvs/keys/test_1_0

echo "---------------------------------------------------------------------------------------------------------------------------------"

#curl --request   GET \
# --header    "Content-Type: application/json" \
# --write-out "%{http_code}\n" \
#http://localhost:13801/recon

#echo "----------------------------------------------------------------------------------------------------------------------------------"


#curl --request   PUT \
# --header    "Content-Type: application/json" \
# --write-out "%{http_code}\n" \
# --data '{"value": "127"}' \
# http://localhost:13801/store_key/v

#echo "-----------------------------------------------------------------------------------------------------------------------------------"


#curl --request GET \
# --header "Content-Type: application/json" \
# --write-out "%{http_code}\n" \
# http://localhost:13801/recon

